name: Tools build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update runner
        run: sudo apt update && sudo apt install gcc clang build-essential make binutils-dev bison bc flex automake gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu gcc-arm-linux-gnueabi binutils-arm-linux-gnueabi

      - name: Grab latest sources
	run: git clone https://github.com/stedolan/jq ~/jq && mkdir -p ~/jq-bins/x86_64 && mkdir -p ~/jq-bins/aarch64 && mkdir -p ~/jq-bins/armhf && mkdir -p ~/jq-bins/i686

      - name: Fetch submodules for 'jq'
	run: cd ~/jq && git submodule update --init

      - name: Build 'jq' for x86_64
	run: |
	    cd ~/jq
	    rm -rf jq
	    autoreconf -i
	    ./configure --with-oniguruma=builtin LDFLAGS="-static -pthread"
	    make -j2 LDFLAGS=-all-static
	    mv jq ~/jq-bins/x86_64/jq

      - name: Build 'jq' for aarch64
        run: |   
            cd ~/jq
	    rm -rf jq  
            autoreconf -i
            ./configure --with-oniguruma=builtin --build x86_64-pc-linux-gnu --host aarch64-linux-gnu LDFLAGS="-static -pthread"
            make -j2 LDFLAGS=-all-static
	    mv jq ~/jq-bins/aarch64/jq

      - name: Build 'jq' for armhf
        run: |       
            cd ~/jq
	    rm -rf jq
            autoreconf -i
            ./configure --with-oniguruma=builtin --build x86_64-pc-linux-gnu --host arm-linux-gnueabi LDFLAGS="-static -pthread"
            make -j2 LDFLAGS=-all-static
	    mv jq ~/jq-bins/armhf/jq

      - name: Build 'jq' for i686 (32bit)
	run: |
	    cd ~/jq
	    rm -rf jq
	    autoreconf -i
	    ./configure --with-oniguruma=builtin --build x86_64-pc-linux-gnu --host i686-pc-linux-gnu LDFLAGS="-static -pthread"
	    make -j2 LDFLAGS--all-static
	    mv jq ~/jq-bins/i686/jq

      - name: Pack up binaries into xz packages
	run: |
	    mkdir ~/packed-bins
	    tar -cJf ~/packed-bins/ubcli_tools-aarch64.tar.xz ~/jq-bins/aarch64/jq
	    tar -cJf ~/packed-bins/ubcli_tools-armhf.tar.xz ~/jq-bins/armhf/jq
	    tar -cJf ~/packed-bins/ubcli_tools-amd64.tar.xz ~/jq-bins/x86_64/jq
	    tar -cJf ~?packed-bins/ubcli_tools-i386.tar.xz ~/jq-bins/i686/jq

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ~/packed-bins/*
          fail_on_unmatched_files: true
